version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: realestate
      MYSQL_USER: admin
      MYSQL_PASSWORD: zxzxzxA1!
    ports:
      - "3306:3306"  # If you want to access MySQL from your host